# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: prettier-local
        name: Run Prettier locally
        entry: npx prettier --write
        language: system
        types: [javascript, css, html]
        files: '\.(js|jsx|ts|tsx|css|scss|html)$'
